# --- Configuration Variables ---

CC = gcc
TARGET = app

SRC_DIR = src
INCLUDE_DIR = include

BUILD_DIR_DEBUG = build/debug
BUILD_DIR_RELEASE = build/release

# Default build type is debug if none is specified
BUILD ?= debug

ifeq ($(BUILD), release)
    BUILD_DIR = $(BUILD_DIR_RELEASE)
    # Release flags: Optimization level 3, no debug info, NDEBUG macro defined
    # Strict warnings: -std=c99 -Wall -Wextra -Wpedantic -Werror (treat warnings as errors)
    CFLAGS += -O3 -DNDEBUG -std=c99 -Wall -Wextra -Wpedantic -Werror
else
    BUILD_DIR = $(BUILD_DIR_DEBUG)
    # Debug flags: Optimization level 0, debug info (-g), DDEBUG macro defined
    # Strict warnings: -std=c99 -Wall -Wextra -Wpedantic -Werror
    CFLAGS += -O0 -g -DDEBUG -std=c99 -Wall -Wextra -Wpedantic -Werror
endif

# Common flags: Add include directory and generate dependency files
CPPFLAGS = -I$(INCLUDE_DIR) -MMD -MP
# LDFLAGS can be used for linker flags if needed
LDFLAGS =

# Find all source files in the source directory
SRCS := $(shell find $(SRC_DIR) -name "*.c")
# Generate corresponding object file paths in the build directory
OBJS := $(patsubst $(SRC_DIR)/%.c,$(BUILD_DIR)/%.o,$(SRCS))
# Generate dependency file paths
DEPS := $(OBJS:.o=.d)

# The first target is the default, which is configured as debug by default
.DEFAULT_GOAL := all

# --- Targets ---

.PHONY: all clean debug release

all: $(BUILD_DIR)/$(TARGET)

debug:
	@$(MAKE) all BUILD=debug

release:
	@$(MAKE) all BUILD=release

# Rule to create necessary build directories
$(BUILD_DIR)/$(TARGET): $(OBJS) | $(BUILD_DIR)
	@echo "Linking $(BUILD) build: $@"
	$(CC) $(LDFLAGS) $^ -o $@

# Generic rule to compile source files into object files in the build directory
$(BUILD_DIR)/%.o: $(SRC_DIR)/%.c | $(BUILD_DIR)
	@echo "Compiling $(BUILD) $< -> $@"
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $< -o $@

# Rule to create build directories if they don't exist
$(BUILD_DIR):
	@mkdir -p $@

clean:
	@echo "Cleaning up build directories..."
	$(RM) -r build

# Include dependency files (automatically generated by -MMD -MP flags)
-include $(DEPS)
